/**
 * Config Manager — Apply received config to local filesystem
 *
 * Handles:
 *   - Writing role markdown files (agents.md, soul.md, etc.)
 *   - Storing API key config for LLM access
 *   - Tracking applied revision to avoid redundant writes
 *   - Persisting state to disk for crash recovery
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { NodeConfig, ConfigManagerOptions, KeyConfigEntry } from "./types.js";

interface PersistedState {
  appliedRevision: number;
  lastAppliedAt: string;
  roleId: string | null;
}

export class ConfigManager {
  private readonly configDir: string;
  private readonly winclawHome: string;
  private readonly onApplied?: (config: NodeConfig) => void | Promise<void>;
  private readonly onError?: (error: Error, config: NodeConfig) => void | Promise<void>;
  private appliedRevision = 0;

  constructor(options: ConfigManagerOptions) {
    this.configDir = options.configDir;
    this.winclawHome = options.winclawHome ?? path.join(os.homedir(), ".winclaw");
    this.onApplied = options.onConfigApplied;
    this.onError = options.onConfigError;

    // Ensure config directory exists
    fs.mkdirSync(this.configDir, { recursive: true });

    // Load persisted state
    this.loadState();
  }

  /** Current applied revision */
  get currentRevision(): number {
    return this.appliedRevision;
  }

  /**
   * Apply a config to the local filesystem.
   * Returns true if applied, false if already at this revision.
   */
  async applyConfig(config: NodeConfig): Promise<boolean> {
    // Skip if already applied
    if (config.revision <= this.appliedRevision) {
      return false;
    }

    try {
      // 1. Write role markdown files
      await this.writeFiles(config.files);

      // 2. Write key config
      if (config.key_config) {
        await this.writeKeyConfig(config.key_config);
      }

      // 3. Write metadata
      await this.writeMetadata(config);

      // 4. Update state
      this.appliedRevision = config.revision;
      this.saveState(config);

      // 5. Notify callback
      if (this.onApplied) {
        await this.onApplied(config);
      }

      return true;
    } catch (err) {
      const error = err instanceof Error ? err : new Error(String(err));
      if (this.onError) {
        await this.onError(error, config);
      }
      throw error;
    }
  }

  // ── File Writing ──────────────────────────────

  private async writeFiles(files: Record<string, string>): Promise<void> {
    const filesDir = path.join(this.configDir, "files");
    fs.mkdirSync(filesDir, { recursive: true });

    for (const [filename, content] of Object.entries(files)) {
      // Sanitize filename to prevent path traversal
      const safeName = path.basename(filename);
      const filePath = path.join(filesDir, safeName);
      fs.writeFileSync(filePath, content, "utf-8");
    }
  }

  private async writeKeyConfig(
    keyConfig: NonNullable<NodeConfig["key_config"]>,
  ): Promise<void> {
    const keysDir = path.join(this.configDir, "keys");
    fs.mkdirSync(keysDir, { recursive: true });

    // Write key config as JSON (the node application reads this at runtime)
    const keyConfigPath = path.join(keysDir, "llm-keys.json");
    fs.writeFileSync(
      keyConfigPath,
      JSON.stringify(keyConfig, null, 2),
      "utf-8",
    );

    // Also write individual env-style files for easy consumption
    if (keyConfig.primary) {
      this.writeEnvKeyFile(keysDir, "primary", keyConfig.primary);
    }
    if (keyConfig.auxiliary) {
      this.writeEnvKeyFile(keysDir, "auxiliary", keyConfig.auxiliary);
    }

    // Sync into winclaw.json so the chat UI can discover the model
    try {
      this.syncToWinclawJson(keyConfig);
    } catch {
      // Non-fatal: llm-keys.json was written successfully
    }
  }

  private writeEnvKeyFile(
    dir: string,
    category: string,
    entry: { provider: string; model: string; apiKey: string; baseUrl?: string },
  ): void {
    const lines: string[] = [
      `# ${category.toUpperCase()} LLM Key — Auto-generated by GRC`,
      `# DO NOT EDIT — managed by GRC config sync`,
      `LLM_PROVIDER=${entry.provider}`,
      `LLM_MODEL=${entry.model}`,
      `LLM_API_KEY=${entry.apiKey}`,
    ];
    if (entry.baseUrl) {
      lines.push(`LLM_BASE_URL=${entry.baseUrl}`);
    }
    fs.writeFileSync(path.join(dir, `${category}.env`), lines.join("\n") + "\n", "utf-8");
  }

  private async writeMetadata(config: NodeConfig): Promise<void> {
    const meta = {
      revision: config.revision,
      role_id: config.role_id,
      role_mode: config.role_mode,
      applied_at: new Date().toISOString(),
      file_count: Object.keys(config.files).length,
      has_primary_key: !!config.key_config?.primary,
      has_auxiliary_key: !!config.key_config?.auxiliary,
    };
    fs.writeFileSync(
      path.join(this.configDir, "config-meta.json"),
      JSON.stringify(meta, null, 2),
      "utf-8",
    );
  }

  // ── WinClaw JSON Sync ─────────────────────────

  /**
   * Detect the WinClaw API wire format from provider/baseUrl.
   */
  private detectApiType(
    provider: string,
    baseUrl?: string,
  ): string {
    const url = baseUrl ?? "";
    const prov = provider.toLowerCase();
    if (url.includes("anthropic") || prov === "anthropic" || prov === "glm") {
      return "anthropic-messages";
    }
    if (url.includes(":11434") || prov.includes("ollama")) {
      return "ollama";
    }
    if (prov === "google") {
      return "google-generative-ai";
    }
    return "openai-completions";
  }

  /**
   * Normalise baseUrl for the detected api type.
   * Ollama native API expects no /v1 suffix and uses 127.0.0.1.
   */
  private normalizeBaseUrl(baseUrl: string, apiType: string): string {
    if (apiType === "ollama") {
      return baseUrl
        .replace(/\/v1\/?$/, "")
        .replace(/localhost/g, "127.0.0.1");
    }
    return baseUrl;
  }

  /**
   * Build a WinClaw provider entry from a KeyConfigEntry.
   */
  private buildProviderEntry(
    entry: KeyConfigEntry,
  ): Record<string, unknown> {
    const apiType = this.detectApiType(entry.provider, entry.baseUrl);
    const baseUrl = entry.baseUrl
      ? this.normalizeBaseUrl(entry.baseUrl, apiType)
      : undefined;

    return {
      ...(baseUrl ? { baseUrl } : {}),
      api: apiType,
      apiKey: entry.apiKey,
      models: [
        {
          id: entry.model,
          name: entry.model,
          reasoning: false,
          input: ["text"],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 32768,
          maxTokens: 8192,
        },
      ],
    };
  }

  /**
   * Sync key_config into winclaw.json's models.providers section
   * so the chat UI can discover and use GRC-pushed models.
   */
  private syncToWinclawJson(
    keyConfig: NonNullable<NodeConfig["key_config"]>,
  ): void {
    const winclawJsonPath = path.join(this.winclawHome, "winclaw.json");
    const grcProvidersPath = path.join(this.winclawHome, ".grc-key-providers.json");

    // Read existing winclaw.json
    let winclaw: Record<string, unknown>;
    try {
      winclaw = JSON.parse(fs.readFileSync(winclawJsonPath, "utf-8"));
    } catch {
      // No winclaw.json — skip sync
      return;
    }

    // Ensure models.providers exists
    const models = (winclaw.models ?? {}) as Record<string, unknown>;
    const providers = (models.providers ?? {}) as Record<string, unknown>;

    const grcProviderNames: string[] = [];

    // Primary → "custom" provider
    if (keyConfig.primary) {
      providers.custom = this.buildProviderEntry(keyConfig.primary);
      grcProviderNames.push("custom");
    }

    // Auxiliary → "google" provider (if present)
    if (keyConfig.auxiliary) {
      providers.google = this.buildProviderEntry(keyConfig.auxiliary);
      grcProviderNames.push("google");
    }

    models.providers = providers;
    winclaw.models = models;

    // Update agents.defaults.model and models alias to match primary
    if (keyConfig.primary) {
      const agents = (winclaw.agents ?? {}) as Record<string, unknown>;
      const defaults = (agents.defaults ?? {}) as Record<string, unknown>;
      const modelRef = `custom/${keyConfig.primary.model}`;
      defaults.model = modelRef;
      defaults.models = {
        [modelRef]: { alias: keyConfig.primary.model },
      };
      agents.defaults = defaults;
      winclaw.agents = agents;
    }

    // Write back winclaw.json
    fs.writeFileSync(winclawJsonPath, JSON.stringify(winclaw, null, 2), "utf-8");

    // Update .grc-key-providers.json
    fs.writeFileSync(
      grcProvidersPath,
      JSON.stringify({ providers: grcProviderNames }),
      "utf-8",
    );
  }

  // ── State Persistence ─────────────────────────

  private get statePath(): string {
    return path.join(this.configDir, ".sync-state.json");
  }

  private loadState(): void {
    try {
      if (fs.existsSync(this.statePath)) {
        const raw = fs.readFileSync(this.statePath, "utf-8");
        const state = JSON.parse(raw) as PersistedState;
        this.appliedRevision = state.appliedRevision ?? 0;
      }
    } catch {
      // Corrupt state file — start fresh
      this.appliedRevision = 0;
    }
  }

  private saveState(config: NodeConfig): void {
    const state: PersistedState = {
      appliedRevision: config.revision,
      lastAppliedAt: new Date().toISOString(),
      roleId: config.role_id,
    };
    fs.writeFileSync(this.statePath, JSON.stringify(state, null, 2), "utf-8");
  }
}
